POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "username": "Stefanie",
    "name": "Stefanie Lim",
    "password": "secret",
    "location": "Central Akl",
    "quote": "Sweeten your life with tea"
}

